apiVersion: v1
kind: Service
metadata:
  name: feature-flag-api
  namespace: feature-flag
spec:
  selector:
    app: feature-flag-api
  ports:
    - name: http
      port: 4000
      targetPort: http
  type: ClusterIP