apiVersion: v1
kind: Service
metadata:
  name: gateway-ui
  namespace: feature-flag
spec:
  selector:
    app: gateway-ui
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP